// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: email_notifications.sql

package models

import (
	"context"

	"github.com/google/uuid"
)

const createEmailNotification = `-- name: CreateEmailNotification :exec
INSERT INTO email_notifications (notification_id, sent_to)
VALUES ($1, $2)
`

type CreateEmailNotificationParams struct {
	NotificationID uuid.UUID `json:"notification_id"`
	SentTo         string    `json:"sent_to"`
}

func (q *Queries) CreateEmailNotification(ctx context.Context, arg CreateEmailNotificationParams) error {
	_, err := q.db.Exec(ctx, createEmailNotification, arg.NotificationID, arg.SentTo)
	return err
}
