// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package models

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateEmailNotification(ctx context.Context, arg CreateEmailNotificationParams) error
	CreateNotification(ctx context.Context, arg CreateNotificationParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetNotificationById(ctx context.Context, id uuid.UUID) (Notification, error)
	GetNotificationsByUserId(ctx context.Context, userID uuid.UUID) ([]Notification, error)
	GetUserById(ctx context.Context, id uuid.UUID) (User, error)
	TruncateUsers(ctx context.Context) error
	UpdateNotificationStatusById(ctx context.Context, arg UpdateNotificationStatusByIdParams) error
}

var _ Querier = (*Queries)(nil)
